# Generated by Django 5.2.7 on 2025-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_usuario_nomeusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(unique=True),
        ),
    ]
