# Generated by Django 5.2.5 on 2025-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='emailUsuario',
            field=models.CharField(),
        ),
    ]
