# Generated by Django 5.2.5 on 2025-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_usuario_emailusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='emailUsuario',
            field=models.EmailField(max_length=254),
        ),
    ]
