# Generated by Django 5.2.5 on 2025-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_tarefa_prioridade_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Fazer', 'Fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')]),
        ),
    ]
