# Generated by Django 5.2.6 on 2025-09-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_tarefa_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario'),
        ),
    ]
