# Generated by Django 5.2.6 on 2025-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_tarefa_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Fazer', 'Fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], null=True),
        ),
    ]
