# Generated by Django 5.2.6 on 2025-09-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_tarefa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='idTarefa',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
